### ISSUE TITLE
How to I run chapters client

### ISSUE THREAD

**Issue by alexw668** [bananaoomarang/chapters#2]
This is really just a question: I'd like to play around with this client app, but it requires 'chapters-server', which is a separate server app. When I run the client, I got "Cannot find module 'chapters-server'" error. How do I get the client to start the 'chapters-server'?

Thanks.

**Comment by bananaoomarang** [comment]
Hey, first I'll warn you that Chapters isn't nearly ready as a product yet (buggy, MVP implementation in progress as a figure it out), so it's only useful as a Redux-y demo and perhaps curiosity. That's why there aren't setup instructions yet, but I'd love for anyone to mess around/take a look at the code.

Here's some instructions from the top of my head:
1. Install and start [CouchDB](http://couchdb.apache.org/) (if on Linux from your distro's package manager) 
2. Clone the [API server](https://github.com/bananaoomarang/chapters-server)
3. Set it up with `chapters-server` with `npm i && npm run init`. 'init' should set up the necessary databases + views in your couch instance.
4. Run `sudo npm link` in `chapters-server`
5. Clone this repo, run `npm i` (if there's issues with `node-sass` you may have to use an earlier version of Node/IOJS)

Then `npm start`/`npm run dev`/`npm run build` should be working here.

That should work for poking around. If you're interested in what it actually is/wants to be, once I start dogfooding it a little myself (fingers crossed within six months, hah) I will write up a proper README and possibly deploy a landing page and possibly Beta.
